# Generated by Django 4.1.7 on 2025-10-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipre_image',
            new_name='recipe_image',
        ),
    ]
